### ISSUE TITLE
Chat about Mathbox + npm publishing for threestrap

### ISSUE THREAD

**Issue by sritchie** [ChristopherChudzicki/math3d-next#21]
Christopher,

Sorry to make this new issue... I still don't have your email!

Following up on https://github.com/ChristopherChudzicki/math3d-react/issues/302, the upgrade is completely finished, and I'm ready to publish threestrap, shadergraph and mathbox.

It looks like you still have the publication rights for `threestrap` (https://www.npmjs.com/package/threestrap). Would you mind adding me (sritchie) to the project on npm?

Also, I'd love to talk about math3d and make sure that these new packages work for you before I push too far ahead with my other work. Send me a note at sritchie09@gmail.com and let's get some time scheduled!

Cheers,
Sam

**Comment by ChristopherChudzicki** [comment]
Going to close this since we've now chatted twice, and mathbox-react is underway :)
